server:
  port: 9000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    userName: tcc
    password: tcc


# H2
spring
---
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url:  jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
---