server:
  context-path: /tcc
  port: 9000

# H2
spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url:  jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update